// Code generated by gowsdl DO NOT EDIT.

package session

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type VsipType string

const (
	VsipTypeIpboth VsipType = "ipboth"

	VsipTypeIPv4 VsipType = "IPv4"

	VsipTypeIPv6 VsipType = "IPv6"
)

type GetPanelSettings struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getPanelSettings"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetPanelSettingsResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getPanelSettingsResponse"`

	Return_ *PanelSettings `xml:"return,omitempty" json:"return,omitempty"`
}

type PanelSettings struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ panelSettings"`

	Language string `xml:"language,omitempty" json:"language,omitempty"`

	PasswordlessMode bool `xml:"passwordlessMode,omitempty" json:"passwordlessMode,omitempty"`

	SecureAccessMode bool `xml:"secureAccessMode,omitempty" json:"secureAccessMode,omitempty"`

	ShowNickname bool `xml:"showNickname,omitempty" json:"showNickname,omitempty"`

	WebserviceEnabled bool `xml:"webserviceEnabled,omitempty" json:"webserviceEnabled,omitempty"`
}

type GetVServerProcesses struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerProcesses"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerProcessesResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerProcessesResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerIPs struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerIPs"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerIPsResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerIPsResponse"`

	Return_ []*string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerUpdateNotification struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerUpdateNotification"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerUpdateNotificationResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerUpdateNotificationResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type ChangeUserPassword struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ changeUserPassword"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	OldPassword string `xml:"oldPassword,omitempty" json:"oldPassword,omitempty"`

	NewPassword string `xml:"newPassword,omitempty" json:"newPassword,omitempty"`
}

type ChangeUserPasswordResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ changeUserPasswordResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerReset struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerReset"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerResetResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerResetResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerResume struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerResume"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerResumeResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerResumeResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerStart struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerStart"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerStartResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerStartResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type SendPasswordResetRequest struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ sendPasswordResetRequest"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	EMail string `xml:"eMail,omitempty" json:"eMail,omitempty"`
}

type SendPasswordResetRequestResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ sendPasswordResetRequestResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type GetFirewall struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getFirewall"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetFirewallResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getFirewallResponse"`

	Return_ []*VsFilter `xml:"return,omitempty" json:"return,omitempty"`
}

type VsFilter struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vsFilter"`

	Comment string `xml:"comment,omitempty" json:"comment,omitempty"`

	Deactivated bool `xml:"deactivated,omitempty" json:"deactivated,omitempty"`

	DestIP string `xml:"destIP,omitempty" json:"destIP,omitempty"`

	DestPort string `xml:"destPort,omitempty" json:"destPort,omitempty"`

	DestPortRange string `xml:"destPortRange,omitempty" json:"destPortRange,omitempty"`

	Direction string `xml:"direction,omitempty" json:"direction,omitempty"`

	Id string `xml:"id,omitempty" json:"id,omitempty"`

	Iptype *VsipType `xml:"iptype,omitempty" json:"iptype,omitempty"`

	Match string `xml:"match,omitempty" json:"match,omitempty"`

	MatchValue string `xml:"matchValue,omitempty" json:"matchValue,omitempty"`

	Proto string `xml:"proto,omitempty" json:"proto,omitempty"`

	Sort string `xml:"sort,omitempty" json:"sort,omitempty"`

	SrcIP string `xml:"srcIP,omitempty" json:"srcIP,omitempty"`

	SrcPort string `xml:"srcPort,omitempty" json:"srcPort,omitempty"`

	SrcPortRange string `xml:"srcPortRange,omitempty" json:"srcPortRange,omitempty"`

	Target string `xml:"target,omitempty" json:"target,omitempty"`

	Valid bool `xml:"valid,omitempty" json:"valid,omitempty"`
}

type VServerSuspend struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerSuspend"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerSuspendResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerSuspendResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type GetUserData struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getUserData"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetUserDataResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getUserDataResponse"`

	Return_ *UserDataObject `xml:"return,omitempty" json:"return,omitempty"`
}

type UserDataObject struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ userDataObject"`

	City string `xml:"city,omitempty" json:"city,omitempty"`

	Company string `xml:"company,omitempty" json:"company,omitempty"`

	Email string `xml:"email,omitempty" json:"email,omitempty"`

	Firstname string `xml:"firstname,omitempty" json:"firstname,omitempty"`

	Lastname string `xml:"lastname,omitempty" json:"lastname,omitempty"`

	Loginname string `xml:"loginname,omitempty" json:"loginname,omitempty"`

	Postcode string `xml:"postcode,omitempty" json:"postcode,omitempty"`

	Street string `xml:"street,omitempty" json:"street,omitempty"`
}

type GetLoginToken struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getLoginToken"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetLoginTokenResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getLoginTokenResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerInformation struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerInformation"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`

	Language string `xml:"language,omitempty" json:"language,omitempty"`
}

type GetVServerInformationResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerInformationResponse"`

	Return_ *VServerInformationObject `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerInformationObject struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerInformationObject"`

	CpuCores int32 `xml:"cpuCores,omitempty" json:"cpuCores,omitempty"`

	CurrentMonth *TrafficMonthObject `xml:"currentMonth,omitempty" json:"currentMonth,omitempty"`

	Ips []*string `xml:"ips,omitempty" json:"ips,omitempty"`

	Memory int64 `xml:"memory,omitempty" json:"memory,omitempty"`

	RebootRecommended bool `xml:"rebootRecommended,omitempty" json:"rebootRecommended,omitempty"`

	RebootRecommendedMessage string `xml:"rebootRecommendedMessage,omitempty" json:"rebootRecommendedMessage,omitempty"`

	RescueEnabled bool `xml:"rescueEnabled,omitempty" json:"rescueEnabled,omitempty"`

	RescueEnabledMessage string `xml:"rescueEnabledMessage,omitempty" json:"rescueEnabledMessage,omitempty"`

	ServerDisks []*ServerDisk `xml:"serverDisks,omitempty" json:"serverDisks,omitempty"`

	ServerInterfaces []*ServerInterface `xml:"serverInterfaces,omitempty" json:"serverInterfaces,omitempty"`

	Status string `xml:"status,omitempty" json:"status,omitempty"`

	Uptime string `xml:"uptime,omitempty" json:"uptime,omitempty"`

	VServerName string `xml:"vServerName,omitempty" json:"vServerName,omitempty"`

	VServerNickname string `xml:"vServerNickname,omitempty" json:"vServerNickname,omitempty"`
}

type TrafficMonthObject struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ trafficMonthObject"`

	In int64 `xml:"in,omitempty" json:"in,omitempty"`

	Month int32 `xml:"month,omitempty" json:"month,omitempty"`

	Out int64 `xml:"out,omitempty" json:"out,omitempty"`

	Total int64 `xml:"total,omitempty" json:"total,omitempty"`

	Year int32 `xml:"year,omitempty" json:"year,omitempty"`
}

type ServerDisk struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ serverDisk"`

	Capacity int64 `xml:"capacity,omitempty" json:"capacity,omitempty"`

	Driver string `xml:"driver,omitempty" json:"driver,omitempty"`

	Name string `xml:"name,omitempty" json:"name,omitempty"`

	OptimizationRecommended bool `xml:"optimizationRecommended,omitempty" json:"optimizationRecommended,omitempty"`

	OptimizationRecommendedMessage string `xml:"optimizationRecommendedMessage,omitempty" json:"optimizationRecommendedMessage,omitempty"`

	Used int64 `xml:"used,omitempty" json:"used,omitempty"`
}

type ServerInterface struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ serverInterface"`

	Driver string `xml:"driver,omitempty" json:"driver,omitempty"`

	Id string `xml:"id,omitempty" json:"id,omitempty"`

	Ipv4IP []*string `xml:"ipv4IP,omitempty" json:"ipv4IP,omitempty"`

	Ipv6IP []*string `xml:"ipv6IP,omitempty" json:"ipv6IP,omitempty"`

	Mac string `xml:"mac,omitempty" json:"mac,omitempty"`

	TrafficThrottled bool `xml:"trafficThrottled,omitempty" json:"trafficThrottled,omitempty"`

	TrafficThrottledMessage string `xml:"trafficThrottledMessage,omitempty" json:"trafficThrottledMessage,omitempty"`
}

type VServerPoweroff struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerPoweroff"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerPoweroffResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerPoweroffResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerStatToken struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerStatToken"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerStatTokenResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerStatTokenResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerState struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerState"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerStateResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerStateResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type ChangeIPRouting struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ changeIPRouting"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	RoutedIP string `xml:"routedIP,omitempty" json:"routedIP,omitempty"`

	RoutedMask string `xml:"routedMask,omitempty" json:"routedMask,omitempty"`

	DestinationVserverName string `xml:"destinationVserverName,omitempty" json:"destinationVserverName,omitempty"`

	DestinationInterfaceMAC string `xml:"destinationInterfaceMAC,omitempty" json:"destinationInterfaceMAC,omitempty"`
}

type ChangeIPRoutingResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ changeIPRoutingResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type AddFirewallRule struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ addFirewallRule"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`

	Rule []*FilterObject `xml:"rule,omitempty" json:"rule,omitempty"`
}

type FilterObject struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ filterObject"`

	Comment string `xml:"comment,omitempty" json:"comment,omitempty"`

	Deactivated string `xml:"deactivated,omitempty" json:"deactivated,omitempty"`

	DestIP string `xml:"destIP,omitempty" json:"destIP,omitempty"`

	DestPort string `xml:"destPort,omitempty" json:"destPort,omitempty"`

	DestPortRange string `xml:"destPortRange,omitempty" json:"destPortRange,omitempty"`

	Direction string `xml:"direction,omitempty" json:"direction,omitempty"`

	Id string `xml:"id,omitempty" json:"id,omitempty"`

	Match string `xml:"match,omitempty" json:"match,omitempty"`

	MatchValue string `xml:"matchValue,omitempty" json:"matchValue,omitempty"`

	Proto string `xml:"proto,omitempty" json:"proto,omitempty"`

	Sort string `xml:"sort,omitempty" json:"sort,omitempty"`

	SrcIP string `xml:"srcIP,omitempty" json:"srcIP,omitempty"`

	SrcPort string `xml:"srcPort,omitempty" json:"srcPort,omitempty"`

	SrcPortRange string `xml:"srcPortRange,omitempty" json:"srcPortRange,omitempty"`

	Target string `xml:"target,omitempty" json:"target,omitempty"`

	Valid string `xml:"valid,omitempty" json:"valid,omitempty"`
}

type AddFirewallRuleResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ addFirewallRuleResponse"`

	Return_ *WebServiceSimpleResult `xml:"return,omitempty" json:"return,omitempty"`
}

type WebServiceSimpleResult struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ webServiceSimpleResult"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`

	Success bool `xml:"success,omitempty" json:"success,omitempty"`
}

type GetVServerLogEntryCount struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLogEntryCount"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`
}

type GetVServerLogEntryCountResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLogEntryCountResponse"`

	Return_ int64 `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerUptime struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerUptime"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerUptimeResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerUptimeResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type DeleteFirewallRule struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ deleteFirewallRule"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`

	Rule []*FilterObject `xml:"rule,omitempty" json:"rule,omitempty"`
}

type DeleteFirewallRuleResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ deleteFirewallRuleResponse"`

	Return_ *WebServiceSimpleResult `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerTrafficOfMonth struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerTrafficOfMonth"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`

	Year int32 `xml:"year,omitempty" json:"year,omitempty"`

	Month int32 `xml:"month,omitempty" json:"month,omitempty"`
}

type GetVServerTrafficOfMonthResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerTrafficOfMonthResponse"`

	Return_ *TrafficMonthObject `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerLogEntries struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLogEntries"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`

	Start int32 `xml:"start,omitempty" json:"start,omitempty"`

	Results int32 `xml:"results,omitempty" json:"results,omitempty"`

	Language string `xml:"language,omitempty" json:"language,omitempty"`
}

type GetVServerLogEntriesResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLogEntriesResponse"`

	Return_ []*LogEntry `xml:"return,omitempty" json:"return,omitempty"`
}

type LogEntry struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ logEntry"`

	AdditionalInfo string `xml:"additionalInfo,omitempty" json:"additionalInfo,omitempty"`

	Date soap.XSDDateTime `xml:"date,omitempty" json:"date,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`

	Type_ string `xml:"type,omitempty" json:"type,omitempty"`
}

type VServerACPIReboot struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerACPIReboot"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerACPIRebootResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerACPIRebootResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type StopVServer struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ stopVServer"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type StopVServerResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ stopVServerResponse"`

	Return_ *WebServiceSimpleResult `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerTrafficOfDay struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerTrafficOfDay"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`

	Year int32 `xml:"year,omitempty" json:"year,omitempty"`

	Month int32 `xml:"month,omitempty" json:"month,omitempty"`

	Day int32 `xml:"day,omitempty" json:"day,omitempty"`
}

type GetVServerTrafficOfDayResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerTrafficOfDayResponse"`

	Return_ *TrafficDayObject `xml:"return,omitempty" json:"return,omitempty"`
}

type TrafficDayObject struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ trafficDayObject"`

	*TrafficMonthObject

	Day int32 `xml:"day,omitempty" json:"day,omitempty"`
}

type GetVServerNickname struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerNickname"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`
}

type GetVServerNicknameResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerNicknameResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type SetVServerNickname struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ setVServerNickname"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`

	Vservernickname string `xml:"vservernickname,omitempty" json:"vservernickname,omitempty"`
}

type SetVServerNicknameResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ setVServerNicknameResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServerLoad struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLoad"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type GetVServerLoadResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServerLoadResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerACPIShutdown struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerACPIShutdown"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerACPIShutdownResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerACPIShutdownResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type GetVServers struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServers"`
	XmlNS   string   `xml:"xmlns:end"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`
}

type GetVServersResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ getVServersResponse"`

	Return_ []*string `xml:"return,omitempty" json:"return,omitempty"`
}

type VServerRestore struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerRestore"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type VServerRestoreResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ vServerRestoreResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type AddCloudVLANInterface struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ addCloudVLANInterface"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	Vservername string `xml:"vservername,omitempty" json:"vservername,omitempty"`

	Cloudvlanid int32 `xml:"cloudvlanid,omitempty" json:"cloudvlanid,omitempty"`

	Driver string `xml:"driver,omitempty" json:"driver,omitempty"`
}

type AddCloudVLANInterfaceResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ addCloudVLANInterfaceResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type StartVServer struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ startVServer"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	VserverName string `xml:"vserverName,omitempty" json:"vserverName,omitempty"`
}

type StartVServerResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ startVServerResponse"`

	Return_ *WebServiceSimpleResult `xml:"return,omitempty" json:"return,omitempty"`
}

type SetPanelSettings struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ setPanelSettings"`

	LoginName string `xml:"loginName,omitempty" json:"loginName,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	ShowNickname bool `xml:"showNickname,omitempty" json:"showNickname,omitempty"`
}

type SetPanelSettingsResponse struct {
	XMLName xml.Name `xml:"http://enduser.service.web.vcp.netcup.de/ setPanelSettingsResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type WSEndUser interface {
	GetLoginToken(request *GetLoginToken) (*GetLoginTokenResponse, error)

	GetLoginTokenContext(ctx context.Context, request *GetLoginToken) (*GetLoginTokenResponse, error)

	ChangeUserPassword(request *ChangeUserPassword) (*ChangeUserPasswordResponse, error)

	ChangeUserPasswordContext(ctx context.Context, request *ChangeUserPassword) (*ChangeUserPasswordResponse, error)

	GetPanelSettings(request *GetPanelSettings) (*GetPanelSettingsResponse, error)

	GetPanelSettingsContext(ctx context.Context, request *GetPanelSettings) (*GetPanelSettingsResponse, error)

	SetPanelSettings(request *SetPanelSettings) (*SetPanelSettingsResponse, error)

	SetPanelSettingsContext(ctx context.Context, request *SetPanelSettings) (*SetPanelSettingsResponse, error)

	SendPasswordResetRequest(request *SendPasswordResetRequest) (*SendPasswordResetRequestResponse, error)

	SendPasswordResetRequestContext(ctx context.Context, request *SendPasswordResetRequest) (*SendPasswordResetRequestResponse, error)

	GetVServers(request *GetVServers) (*GetVServersResponse, error)

	GetVServersContext(ctx context.Context, request *GetVServers) (*GetVServersResponse, error)

	GetVServerInformation(request *GetVServerInformation) (*GetVServerInformationResponse, error)

	GetVServerInformationContext(ctx context.Context, request *GetVServerInformation) (*GetVServerInformationResponse, error)

	GetVServerLogEntryCount(request *GetVServerLogEntryCount) (*GetVServerLogEntryCountResponse, error)

	GetVServerLogEntryCountContext(ctx context.Context, request *GetVServerLogEntryCount) (*GetVServerLogEntryCountResponse, error)

	AddCloudVLANInterface(request *AddCloudVLANInterface) (*AddCloudVLANInterfaceResponse, error)

	AddCloudVLANInterfaceContext(ctx context.Context, request *AddCloudVLANInterface) (*AddCloudVLANInterfaceResponse, error)

	GetVServerLogEntries(request *GetVServerLogEntries) (*GetVServerLogEntriesResponse, error)

	GetVServerLogEntriesContext(ctx context.Context, request *GetVServerLogEntries) (*GetVServerLogEntriesResponse, error)

	GetVServerNickname(request *GetVServerNickname) (*GetVServerNicknameResponse, error)

	GetVServerNicknameContext(ctx context.Context, request *GetVServerNickname) (*GetVServerNicknameResponse, error)

	SetVServerNickname(request *SetVServerNickname) (*SetVServerNicknameResponse, error)

	SetVServerNicknameContext(ctx context.Context, request *SetVServerNickname) (*SetVServerNicknameResponse, error)

	GetVServerState(request *GetVServerState) (*GetVServerStateResponse, error)

	GetVServerStateContext(ctx context.Context, request *GetVServerState) (*GetVServerStateResponse, error)

	GetVServerLoad(request *GetVServerLoad) (*GetVServerLoadResponse, error)

	GetVServerLoadContext(ctx context.Context, request *GetVServerLoad) (*GetVServerLoadResponse, error)

	GetVServerUptime(request *GetVServerUptime) (*GetVServerUptimeResponse, error)

	GetVServerUptimeContext(ctx context.Context, request *GetVServerUptime) (*GetVServerUptimeResponse, error)

	GetVServerProcesses(request *GetVServerProcesses) (*GetVServerProcessesResponse, error)

	GetVServerProcessesContext(ctx context.Context, request *GetVServerProcesses) (*GetVServerProcessesResponse, error)

	GetVServerIPs(request *GetVServerIPs) (*GetVServerIPsResponse, error)

	GetVServerIPsContext(ctx context.Context, request *GetVServerIPs) (*GetVServerIPsResponse, error)

	StartVServer(request *StartVServer) (*StartVServerResponse, error)

	StartVServerContext(ctx context.Context, request *StartVServer) (*StartVServerResponse, error)

	StopVServer(request *StopVServer) (*StopVServerResponse, error)

	StopVServerContext(ctx context.Context, request *StopVServer) (*StopVServerResponse, error)

	GetVServerUpdateNotification(request *GetVServerUpdateNotification) (*GetVServerUpdateNotificationResponse, error)

	GetVServerUpdateNotificationContext(ctx context.Context, request *GetVServerUpdateNotification) (*GetVServerUpdateNotificationResponse, error)

	GetFirewall(request *GetFirewall) (*GetFirewallResponse, error)

	GetFirewallContext(ctx context.Context, request *GetFirewall) (*GetFirewallResponse, error)

	AddFirewallRule(request *AddFirewallRule) (*AddFirewallRuleResponse, error)

	AddFirewallRuleContext(ctx context.Context, request *AddFirewallRule) (*AddFirewallRuleResponse, error)

	DeleteFirewallRule(request *DeleteFirewallRule) (*DeleteFirewallRuleResponse, error)

	DeleteFirewallRuleContext(ctx context.Context, request *DeleteFirewallRule) (*DeleteFirewallRuleResponse, error)

	VServerACPIShutdown(request *VServerACPIShutdown) (*VServerACPIShutdownResponse, error)

	VServerACPIShutdownContext(ctx context.Context, request *VServerACPIShutdown) (*VServerACPIShutdownResponse, error)

	VServerACPIReboot(request *VServerACPIReboot) (*VServerACPIRebootResponse, error)

	VServerACPIRebootContext(ctx context.Context, request *VServerACPIReboot) (*VServerACPIRebootResponse, error)

	VServerReset(request *VServerReset) (*VServerResetResponse, error)

	VServerResetContext(ctx context.Context, request *VServerReset) (*VServerResetResponse, error)

	VServerPoweroff(request *VServerPoweroff) (*VServerPoweroffResponse, error)

	VServerPoweroffContext(ctx context.Context, request *VServerPoweroff) (*VServerPoweroffResponse, error)

	VServerStart(request *VServerStart) (*VServerStartResponse, error)

	VServerStartContext(ctx context.Context, request *VServerStart) (*VServerStartResponse, error)

	VServerSuspend(request *VServerSuspend) (*VServerSuspendResponse, error)

	VServerSuspendContext(ctx context.Context, request *VServerSuspend) (*VServerSuspendResponse, error)

	VServerResume(request *VServerResume) (*VServerResumeResponse, error)

	VServerResumeContext(ctx context.Context, request *VServerResume) (*VServerResumeResponse, error)

	VServerRestore(request *VServerRestore) (*VServerRestoreResponse, error)

	VServerRestoreContext(ctx context.Context, request *VServerRestore) (*VServerRestoreResponse, error)

	GetVServerStatToken(request *GetVServerStatToken) (*GetVServerStatTokenResponse, error)

	GetVServerStatTokenContext(ctx context.Context, request *GetVServerStatToken) (*GetVServerStatTokenResponse, error)

	GetVServerTrafficOfDay(request *GetVServerTrafficOfDay) (*GetVServerTrafficOfDayResponse, error)

	GetVServerTrafficOfDayContext(ctx context.Context, request *GetVServerTrafficOfDay) (*GetVServerTrafficOfDayResponse, error)

	GetVServerTrafficOfMonth(request *GetVServerTrafficOfMonth) (*GetVServerTrafficOfMonthResponse, error)

	GetVServerTrafficOfMonthContext(ctx context.Context, request *GetVServerTrafficOfMonth) (*GetVServerTrafficOfMonthResponse, error)

	ChangeIPRouting(request *ChangeIPRouting) (*ChangeIPRoutingResponse, error)

	ChangeIPRoutingContext(ctx context.Context, request *ChangeIPRouting) (*ChangeIPRoutingResponse, error)

	GetUserData(request *GetUserData) (*GetUserDataResponse, error)

	GetUserDataContext(ctx context.Context, request *GetUserData) (*GetUserDataResponse, error)
}

type wSEndUser struct {
	client *soap.Client
}

func NewWSEndUser(client *soap.Client) WSEndUser {
	return &wSEndUser{
		client: client,
	}
}

func (service *wSEndUser) GetLoginTokenContext(ctx context.Context, request *GetLoginToken) (*GetLoginTokenResponse, error) {
	response := new(GetLoginTokenResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetLoginToken(request *GetLoginToken) (*GetLoginTokenResponse, error) {
	return service.GetLoginTokenContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) ChangeUserPasswordContext(ctx context.Context, request *ChangeUserPassword) (*ChangeUserPasswordResponse, error) {
	response := new(ChangeUserPasswordResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) ChangeUserPassword(request *ChangeUserPassword) (*ChangeUserPasswordResponse, error) {
	return service.ChangeUserPasswordContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetPanelSettingsContext(ctx context.Context, request *GetPanelSettings) (*GetPanelSettingsResponse, error) {
	response := new(GetPanelSettingsResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetPanelSettings(request *GetPanelSettings) (*GetPanelSettingsResponse, error) {
	return service.GetPanelSettingsContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) SetPanelSettingsContext(ctx context.Context, request *SetPanelSettings) (*SetPanelSettingsResponse, error) {
	response := new(SetPanelSettingsResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) SetPanelSettings(request *SetPanelSettings) (*SetPanelSettingsResponse, error) {
	return service.SetPanelSettingsContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) SendPasswordResetRequestContext(ctx context.Context, request *SendPasswordResetRequest) (*SendPasswordResetRequestResponse, error) {
	response := new(SendPasswordResetRequestResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) SendPasswordResetRequest(request *SendPasswordResetRequest) (*SendPasswordResetRequestResponse, error) {
	return service.SendPasswordResetRequestContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServersContext(ctx context.Context, request *GetVServers) (*GetVServersResponse, error) {
	response := new(GetVServersResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServers(request *GetVServers) (*GetVServersResponse, error) {
	return service.GetVServersContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerInformationContext(ctx context.Context, request *GetVServerInformation) (*GetVServerInformationResponse, error) {
	response := new(GetVServerInformationResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerInformation(request *GetVServerInformation) (*GetVServerInformationResponse, error) {
	return service.GetVServerInformationContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerLogEntryCountContext(ctx context.Context, request *GetVServerLogEntryCount) (*GetVServerLogEntryCountResponse, error) {
	response := new(GetVServerLogEntryCountResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerLogEntryCount(request *GetVServerLogEntryCount) (*GetVServerLogEntryCountResponse, error) {
	return service.GetVServerLogEntryCountContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) AddCloudVLANInterfaceContext(ctx context.Context, request *AddCloudVLANInterface) (*AddCloudVLANInterfaceResponse, error) {
	response := new(AddCloudVLANInterfaceResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) AddCloudVLANInterface(request *AddCloudVLANInterface) (*AddCloudVLANInterfaceResponse, error) {
	return service.AddCloudVLANInterfaceContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerLogEntriesContext(ctx context.Context, request *GetVServerLogEntries) (*GetVServerLogEntriesResponse, error) {
	response := new(GetVServerLogEntriesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerLogEntries(request *GetVServerLogEntries) (*GetVServerLogEntriesResponse, error) {
	return service.GetVServerLogEntriesContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerNicknameContext(ctx context.Context, request *GetVServerNickname) (*GetVServerNicknameResponse, error) {
	response := new(GetVServerNicknameResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerNickname(request *GetVServerNickname) (*GetVServerNicknameResponse, error) {
	return service.GetVServerNicknameContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) SetVServerNicknameContext(ctx context.Context, request *SetVServerNickname) (*SetVServerNicknameResponse, error) {
	response := new(SetVServerNicknameResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) SetVServerNickname(request *SetVServerNickname) (*SetVServerNicknameResponse, error) {
	return service.SetVServerNicknameContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerStateContext(ctx context.Context, request *GetVServerState) (*GetVServerStateResponse, error) {
	response := new(GetVServerStateResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerState(request *GetVServerState) (*GetVServerStateResponse, error) {
	return service.GetVServerStateContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerLoadContext(ctx context.Context, request *GetVServerLoad) (*GetVServerLoadResponse, error) {
	response := new(GetVServerLoadResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerLoad(request *GetVServerLoad) (*GetVServerLoadResponse, error) {
	return service.GetVServerLoadContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerUptimeContext(ctx context.Context, request *GetVServerUptime) (*GetVServerUptimeResponse, error) {
	response := new(GetVServerUptimeResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerUptime(request *GetVServerUptime) (*GetVServerUptimeResponse, error) {
	return service.GetVServerUptimeContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerProcessesContext(ctx context.Context, request *GetVServerProcesses) (*GetVServerProcessesResponse, error) {
	response := new(GetVServerProcessesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerProcesses(request *GetVServerProcesses) (*GetVServerProcessesResponse, error) {
	return service.GetVServerProcessesContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerIPsContext(ctx context.Context, request *GetVServerIPs) (*GetVServerIPsResponse, error) {
	response := new(GetVServerIPsResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerIPs(request *GetVServerIPs) (*GetVServerIPsResponse, error) {
	return service.GetVServerIPsContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) StartVServerContext(ctx context.Context, request *StartVServer) (*StartVServerResponse, error) {
	response := new(StartVServerResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) StartVServer(request *StartVServer) (*StartVServerResponse, error) {
	return service.StartVServerContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) StopVServerContext(ctx context.Context, request *StopVServer) (*StopVServerResponse, error) {
	response := new(StopVServerResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) StopVServer(request *StopVServer) (*StopVServerResponse, error) {
	return service.StopVServerContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerUpdateNotificationContext(ctx context.Context, request *GetVServerUpdateNotification) (*GetVServerUpdateNotificationResponse, error) {
	response := new(GetVServerUpdateNotificationResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerUpdateNotification(request *GetVServerUpdateNotification) (*GetVServerUpdateNotificationResponse, error) {
	return service.GetVServerUpdateNotificationContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetFirewallContext(ctx context.Context, request *GetFirewall) (*GetFirewallResponse, error) {
	response := new(GetFirewallResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetFirewall(request *GetFirewall) (*GetFirewallResponse, error) {
	return service.GetFirewallContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) AddFirewallRuleContext(ctx context.Context, request *AddFirewallRule) (*AddFirewallRuleResponse, error) {
	response := new(AddFirewallRuleResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) AddFirewallRule(request *AddFirewallRule) (*AddFirewallRuleResponse, error) {
	return service.AddFirewallRuleContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) DeleteFirewallRuleContext(ctx context.Context, request *DeleteFirewallRule) (*DeleteFirewallRuleResponse, error) {
	response := new(DeleteFirewallRuleResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) DeleteFirewallRule(request *DeleteFirewallRule) (*DeleteFirewallRuleResponse, error) {
	return service.DeleteFirewallRuleContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerACPIShutdownContext(ctx context.Context, request *VServerACPIShutdown) (*VServerACPIShutdownResponse, error) {
	response := new(VServerACPIShutdownResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerACPIShutdown(request *VServerACPIShutdown) (*VServerACPIShutdownResponse, error) {
	return service.VServerACPIShutdownContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerACPIRebootContext(ctx context.Context, request *VServerACPIReboot) (*VServerACPIRebootResponse, error) {
	response := new(VServerACPIRebootResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerACPIReboot(request *VServerACPIReboot) (*VServerACPIRebootResponse, error) {
	return service.VServerACPIRebootContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerResetContext(ctx context.Context, request *VServerReset) (*VServerResetResponse, error) {
	response := new(VServerResetResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerReset(request *VServerReset) (*VServerResetResponse, error) {
	return service.VServerResetContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerPoweroffContext(ctx context.Context, request *VServerPoweroff) (*VServerPoweroffResponse, error) {
	response := new(VServerPoweroffResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerPoweroff(request *VServerPoweroff) (*VServerPoweroffResponse, error) {
	return service.VServerPoweroffContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerStartContext(ctx context.Context, request *VServerStart) (*VServerStartResponse, error) {
	response := new(VServerStartResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerStart(request *VServerStart) (*VServerStartResponse, error) {
	return service.VServerStartContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerSuspendContext(ctx context.Context, request *VServerSuspend) (*VServerSuspendResponse, error) {
	response := new(VServerSuspendResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerSuspend(request *VServerSuspend) (*VServerSuspendResponse, error) {
	return service.VServerSuspendContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerResumeContext(ctx context.Context, request *VServerResume) (*VServerResumeResponse, error) {
	response := new(VServerResumeResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerResume(request *VServerResume) (*VServerResumeResponse, error) {
	return service.VServerResumeContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) VServerRestoreContext(ctx context.Context, request *VServerRestore) (*VServerRestoreResponse, error) {
	response := new(VServerRestoreResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) VServerRestore(request *VServerRestore) (*VServerRestoreResponse, error) {
	return service.VServerRestoreContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerStatTokenContext(ctx context.Context, request *GetVServerStatToken) (*GetVServerStatTokenResponse, error) {
	response := new(GetVServerStatTokenResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerStatToken(request *GetVServerStatToken) (*GetVServerStatTokenResponse, error) {
	return service.GetVServerStatTokenContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerTrafficOfDayContext(ctx context.Context, request *GetVServerTrafficOfDay) (*GetVServerTrafficOfDayResponse, error) {
	response := new(GetVServerTrafficOfDayResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerTrafficOfDay(request *GetVServerTrafficOfDay) (*GetVServerTrafficOfDayResponse, error) {
	return service.GetVServerTrafficOfDayContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetVServerTrafficOfMonthContext(ctx context.Context, request *GetVServerTrafficOfMonth) (*GetVServerTrafficOfMonthResponse, error) {
	response := new(GetVServerTrafficOfMonthResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetVServerTrafficOfMonth(request *GetVServerTrafficOfMonth) (*GetVServerTrafficOfMonthResponse, error) {
	return service.GetVServerTrafficOfMonthContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) ChangeIPRoutingContext(ctx context.Context, request *ChangeIPRouting) (*ChangeIPRoutingResponse, error) {
	response := new(ChangeIPRoutingResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) ChangeIPRouting(request *ChangeIPRouting) (*ChangeIPRoutingResponse, error) {
	return service.ChangeIPRoutingContext(
		context.Background(),
		request,
	)
}

func (service *wSEndUser) GetUserDataContext(ctx context.Context, request *GetUserData) (*GetUserDataResponse, error) {
	response := new(GetUserDataResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *wSEndUser) GetUserData(request *GetUserData) (*GetUserDataResponse, error) {
	return service.GetUserDataContext(
		context.Background(),
		request,
	)
}
